model_select: "kan_two"
#mlp,mlp_two,kan_two,kan
select_dataset: "tox21"
#bbbp, bace, clintox,sider,tox21,hiv,muv
force_field: 'uff'

encoder_atom: "cgcnn"
#encoder_method = ("atomic_number":1, "basic":11, "cfid":438, "cgcnn":92,'self':62,'gme':140)
encoder_bond: "dim_14"

pooing: 'avg'
#max,sum,avg
loss_sclect: 'bce'
grid_feat: 2
num_layers: 3
#l1,l2,sml1,bce
LR: 0.00015
NUM_EPOCHS: 1001
batch_size: 512
train_ratio: 0.8
vali_ratio: 0.1
test_ratio: 0.1
iter: 5
